#!/usr/bin/python

import midi
import sys
import pickle

histogram = [0] * 11
midifile = sys.argv[1]

pattern = midi.read_midifile(midifile)

for event in pattern:
    if isinstance(event, midi.NoteEvent):
        idx = event.pitch / 12
        histogram[idx] += 1

print histogram
print repr(pattern)
